### ISSUE TITLE
terms and conditions web screen

### ISSUE THREAD

**Issue by t-c-team79** [zuri-training/T_C_gen-team-79-frontend#15]

**Comment by funmeelayo** [comment]
design of the terms and conditions progress web screen complete

https://www.figma.com/file/90YRb0uxWaVW0ktVqxUMSy/T_C_GEN-TEAM-79(original)?node-id=1547%3A33258

this is the link to the first page of the progress screen

**Comment by designfairy01** [comment]
Lofi and Hifi  design of privacy policy screen design

https://www.figma.com/file/90YRb0uxWaVW0ktVqxUMSy/T_C_GEN-TEAM-79(original)?node-id=1547%3A33258
