### ISSUE TITLE
User Journey

### ISSUE THREAD

**Issue by Ibukun03** [zuri-training/T_C_gen-team-79-frontend#24]

**Comment by funmeelayo** [comment]
user journey map completed
https://www.figma.com/file/90YRb0uxWaVW0ktVqxUMSy/T_C_GEN-TEAM-79(original)?node-id=1544%3A53853

**Comment by Annaliese-Emenike** [comment]
user journey map completed
https://www.figma.com/file/90YRb0uxWaVW0ktVqxUMSy/T_C_GEN-TEAM-79(original)?node-id=1544%3A53853
